version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass test@123 --dbfilename auth.rdb
    environment:
      - REDIS_DB_NAME=mydb
    restart: always
    networks:
      - redis-network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"  # RedisInsight port
      - "6380:6379"  # Redis Stack port
    volumes:
      - redis-stack-data:/data
    environment:
      - REDIS_ARGS=--requirepass test@123
    depends_on:
      - redis
    networks:
      - redis-network
    restart: always

volumes:
  redis-data:
  redis-stack-data:

networks:
  redis-network:
    driver: bridge